// Use puppeteer-extra and the stealth plugin to avoid bot detection.
import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
import { Browser, Page } from 'puppeteer';
puppeteer.use(StealthPlugin());

const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';
const SEARCH_API_URL = 'https://www.woolworths.com.au/apis/ui/Search/products';

// A unified data model for a product, regardless of the source.
interface Product {
  gtin: string;
  name: string;
  brand: string;
  price: number;
  imageUrl: string;
  size: string;
  store: 'Woolworths' | 'Coles';
  categories: string[];
}

// Interface for the filter structure the API expects.
export interface WoolworthsFilter {
  Key: string;
  Items: { Term: string }[];
}

// Type for the raw data we'll pull from the browser
interface RawScrapedData {
  products: any[];
  aggregations: any[];
  facetFilters: string[];
}

// --- INTELLIGENCE LAYER: DYNAMIC CATEGORIZATION ---

/**
 * Creates a map of categories to search keywords, based on the API's own suggestions.
 * This is the core of the dynamic approach.
 * @param aggregations - The 'Aggregations' array from the API.
 * @param facetFilters - The 'FacetFilters' array from the API.
 * @returns A Map where keys are official categories and values are arrays of keywords to search for.
 */
function buildCategoryKeywordMap(aggregations: any[], facetFilters: string[]): Map<string, string[]> {
  const categoryMap = new Map<string, string[]>();
  const knownSynonyms: { [key: string]: string[] } = {
    'Full Fat': ['full fat', 'full cream', 'whole milk'],
    // Add more known synonyms here for other product types as needed.
  };

  const allFilterTerms = new Set<string>(facetFilters);

  // Extract terms from key aggregations
  const relevantAggregations = ['Allergens', 'Lifestyle'];
  aggregations.forEach(agg => {
    if (relevantAggregations.includes(agg.Name) && agg.ResultsGrouped) {
      agg.ResultsGrouped.forEach((group: any) => {
        group.Filters.forEach((filter: any) => allFilterTerms.add(filter.Name));
      });
    }
  });

  // Build the final map
  allFilterTerms.forEach(term => {
    const keywords = knownSynonyms[term] || [term.toLowerCase()];
    categoryMap.set(term, keywords);
  });

  return categoryMap;
}

/**
 * Assigns categories to a single product by checking its data against the keyword map.
 * @param product - The raw product object from the API.
 * @param categoryMap - The map generated by buildCategoryKeywordMap.
 * @returns An array of matching category strings.
 */
function assignCategoriesToProduct(product: any, categoryMap: Map<string, string[]>): string[] {
  const assignedCategories = new Set<string>();

  // Consolidate all searchable text fields from the product into one string.
  const searchableText = [
    product.DisplayName,
    product.AdditionalAttributes?.description,
    product.AdditionalAttributes?.sapsegmentname,
    product.AdditionalAttributes?.piessubcategorynamesjson,
    product.AdditionalAttributes?.lifestyleanddietarystatement,
    product.AdditionalAttributes?.allergystatement,
  ]
    .join(' ')
    .toLowerCase();

  // Iterate through our dynamic list of possible categories
  for (const [category, keywords] of categoryMap.entries()) {
    // Check if any of the keywords for this category exist in the product's text
    for (const keyword of keywords) {
      if (searchableText.includes(keyword)) {
        assignedCategories.add(category);
        break; // Move to the next category once one keyword matches
      }
    }
  }

  // --- Contradiction Resolution ---
  // If a product is categorized as both Low Fat and Full Fat, use the product name as the tie-breaker.
  if (assignedCategories.has('Low Fat') && assignedCategories.has('Full Fat')) {
    const productName = (product.DisplayName || '').toLowerCase();
    if (productName.includes('low fat') || productName.includes('skim') || productName.includes('lite')) {
      assignedCategories.delete('Full Fat'); // It's definitely a low-fat product.
    }
  }

  return Array.from(assignedCategories);
}


/**
 * Main scraping function, now orchestrating a smarter, decoupled process.
 */
async function scrapeWoolworthsAPI(query: string, filters: WoolworthsFilter[] = []): Promise<Product[]> {
  let browser: Browser | null = null;
  const allEnrichedProducts: Product[] = [];
  console.log(`[ScraperService] Launching browser for query: "${query}" with ${filters.length} filters.`);

  try {
    browser = await puppeteer.launch({
      headless: true,
      dumpio: false,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
    });

    const browserPage = await browser.newPage();
    await browserPage.setUserAgent(USER_AGENT);
    await browserPage.setViewport({ width: 1920, height: 1080 });

    // Navigate to the homepage to establish a valid session with cookies.
    console.log('[ScraperService] Navigating to homepage to establish session...');
    await browserPage.goto('https://www.woolworths.com.au', { waitUntil: 'domcontentloaded' });

    let currentPage = 1;
    let hasMorePages = true;

    while (hasMorePages) {
      console.log(`[ScraperService] Scraping page ${currentPage}...`);
      const rawData: RawScrapedData = await browserPage.evaluate(
        (apiUrl, searchTerm, filterList, pageNum) => {
          return fetch(apiUrl, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              SearchTerm: searchTerm, PageNumber: pageNum, PageSize: 36, SortType: 'TraderRelevance', Filters: filterList,
            }),
          })
          .then(response => {
            if (!response.ok) throw new Error(`API request failed with status ${response.status}`);
            return response.json();
          })
          .then(data => {
            const outerProducts = data.Products || [];
            const allInnerProducts: any[] = [];
            outerProducts.forEach((group: any) => {
              if (group && group.Products) allInnerProducts.push(...group.Products);
            });
            return {
              products: allInnerProducts,
              aggregations: data.Aggregations || [],
              facetFilters: data.FacetFilters || [],
            };
          });
        },
        SEARCH_API_URL, query, filters, currentPage
      );

      if (rawData.products.length === 0) {
        hasMorePages = false;
        console.log(`[ScraperService] Page ${currentPage} has no products. Ending pagination.`);
        continue;
      }

      console.log(`[ScraperService] Scraped ${rawData.products.length} raw products from page ${currentPage}. Now processing...`);

      const categoryMap = buildCategoryKeywordMap(rawData.aggregations, rawData.facetFilters);

      const enrichedProducts: Product[] = rawData.products.map(product => {
        return {
          gtin: product.Barcode || 'N/A',
          name: product.DisplayName,
          brand: product.Brand || 'N/A',
          price: product.Price,
          imageUrl: product.MediumImageFile,
          size: product.PackageSize,
          store: 'Woolworths' as const,
          categories: assignCategoriesToProduct(product, categoryMap),
        };
      });

      allEnrichedProducts.push(...enrichedProducts);
      currentPage++;
    }

    console.log(`[ScraperService] Pagination complete. Total enriched products: ${allEnrichedProducts.length}.`);
    return allEnrichedProducts;

  } catch (error) {
    const err = error as Error;
    console.error(`[ScraperService] An error occurred: ${err.message}`);
    return allEnrichedProducts; // Return whatever was scraped before the error.
  } finally {
    if (browser) {
      console.log('[ScraperService] Closing browser.');
      await browser.close();
    }
  }
}

export const scraperService = {
  // Update the main scrape function to accept filters
  scrape: (target: string, query: string, filters?: WoolworthsFilter[]) => {
    switch (target.toLowerCase()) {
      case 'woolworths':
        return scrapeWoolworthsAPI(query, filters);
      default:
        console.warn(`[ScraperService] No scraper found for target: ${target}`);
        return Promise.resolve([]);
    }
  }
};